#!/usr/bin/python

import sys, getopt
import socket

print socket.gethostbyaddr("176.113.208.1")


def main(argv):
   command = ''
   description = ''
   topic=''
   try:
      opts, args = getopt.getopt(argv,"hc:d:t:",["command=", "description=", "topic="])
   except getopt.GetoptError:
      print 'trackme.py -c <command> -d <description of command> -t <topic>'
      sys.exit(2)

   for opt, arg in opts:
      if opt == '-h':
         print 'trackme.py -c <command> -d <description of command> -t <topic>'
         sys.exit()
      elif opt in ("-c", "--command"):
          command = arg
      elif opt in ("-d", "--description"):
          description = arg
      elif opt in ("-t", "--topic"):
          topic = arg



   print 'Command is ', command
   print 'Description is ', description
   print 'Topic is ' + topic

if __name__ == "__main__":
   main(sys.argv[1:])
